"""Human-readable metadata for Phase 1 DuckDB quality detectors."""

# ruff: noqa: E501

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class DetectorMetadata:
    issue_id: str
    dataset: str
    description: str
    business_impact: str
    detection_severity: str
    proposed_disposition: str
    rationale: str
    pending_human_decision: str
    post_treatment_validation_proposal: str


def detector(
    issue_id: str,
    dataset: str,
    description: str,
    business_impact: str,
    severity: str,
    disposition: str,
    rationale: str,
    decision: str,
    validation: str,
) -> DetectorMetadata:
    return DetectorMetadata(
        issue_id,
        dataset,
        description,
        business_impact,
        severity,
        disposition,
        rationale,
        decision,
        validation,
    )


DETECTORS = (
    detector(
        "SRC-001",
        "all_sources",
        "必填欄位為 NULL、空字串或純空白",
        "型別轉換、key 與分析欄位可能失真。",
        "ERROR",
        "QUARANTINE",
        "無權威值可安全補入。",
        "確認各欄位 nullability 與是否存在可修補來源。",
        "處理後必填欄位 blank count 為 0，隔離數與 evidence 一致。",
    ),
    detector(
        "SRC-002",
        "all_sources",
        "文字值含前後空白",
        "同義值可能被拆成不同 key 或分類。",
        "WARNING",
        "NORMALIZE",
        "trim 通常可逆，仍須保留 raw value。",
        "確認所有識別碼與分類欄位均允許 trim。",
        "正規化後無前後空白且 distinct mapping 可追溯。",
    ),
    detector(
        "ORD-001",
        "orders",
        "完全相同的訂單事件列重複出現",
        "重複計算訂單、數量與金額。",
        "WARNING",
        "NORMALIZE",
        "保留全部 raw rows；canonical staging 依完整 event identity／row hash 去重。",
        "完全相同的 duplicate 不隔離整個 order；保留 duplicate count 與 lineage。",
        "canonical event 唯一，raw/canonical/duplicate counts 與 lineage 可重現。",
    ),
    detector(
        "ORD-002",
        "orders",
        "同一 order_id 有多筆事件",
        "若直接當 fact 載入會重複計算；也可能只是合法狀態歷史。",
        "INFO",
        "ACCEPT",
        "題目明示增量可包含狀態更新。",
        "確認 latest-state grain 與保留事件歷史的方式。",
        "每個 order 的事件序列與 latest candidate 可重現。",
    ),
    detector(
        "ORD-003",
        "orders",
        "同一 order_id、updated_at 有不同 payload",
        "沒有額外 tie-breaker 時 latest state 不唯一。",
        "CRITICAL",
        "QUARANTINE",
        "相同業務時間無法可靠決定勝出事件。",
        "整個 order business key 隔離；不以 source row、file order 或 row hash 選 winner。",
        "所有同時點 conflicting payload 的 order business key 均整組隔離。",
    ),
    detector(
        "ORD-004",
        "orders",
        "同一 order_id 的 invariant candidate 欄位衝突",
        "可能把不同業務實體或錯誤修訂合併。",
        "ERROR",
        "QUARANTINE",
        "同 business key 的非狀態欄位衝突無 correction event type 或權威 sequence。",
        "QUARANTINE 整個衝突 order business key；保留所有 raw events。",
        "每個衝突 key 均整組隔離；不得用 row order 或 row hash 宣稱業務正確 winner。",
    ),
    detector(
        "ORD-005",
        "orders",
        "同一 order_id 的最大 updated_at 有多筆候選",
        "latest selection 可能受未定義排序影響。",
        "ERROR",
        "QUARANTINE",
        "最大時間不保證唯一。",
        "確認相同 latest timestamp 的 duplicate/conflict policy。",
        "每個 order 恰有一個 deterministic latest winner 或整組隔離。",
    ),
    detector(
        "ORD-006",
        "orders",
        "order_status 不在來源 contract domain",
        "狀態分析與 transition 邏輯無法可靠執行。",
        "ERROR",
        "QUARANTINE",
        "未知狀態不可自行映射。",
        "確認上游是否有合法新狀態或 alias。",
        "未知狀態為 0 或全數有核准 mapping。",
    ),
    detector(
        "ORD-007",
        "orders",
        "channel 不在來源 contract domain",
        "通路報表可能拆分類或漏列。",
        "WARNING",
        "NORMALIZE",
        "可能是大小寫或 alias，但需人工確認。",
        "確認通路 alias 與 canonical value。",
        "正規化後 channel 僅含核准 domain。",
    ),
    detector(
        "ORD-008",
        "orders",
        "quantity 無法解析為整數或不為正數",
        "訂單量與金額延伸計算不可信。",
        "ERROR",
        "QUARANTINE",
        "無法由其他欄位權威推導。",
        "確認 quantity 是否允許零或退貨負數。",
        "curated 候選 quantity 均為核准範圍內整數。",
    ),
    detector(
        "ORD-009",
        "orders",
        "raw currency NTD 需要來源限定的 TWD alias 正規化",
        "若不正規化會造成 FX join 缺口；若任意套 rate 1 則可能誤換未知幣別。",
        "WARNING",
        "NORMALIZE",
        "人工決策核准 NTD → TWD，保留 raw currency；只有 TWD/NTD 可使用 rate 1。",
        "此 mapping 已核准為 Phase 2 候選，但 Phase 1 不實作 ETL。",
        "canonical currency 為 TWD、raw currency 保留，其他 missing FX 不得 COALESCE 為 1。",
    ),
    detector(
        "ORD-010",
        "orders",
        "amount 無法解析為 Decimal 或不為正數",
        "收入及金額 reconciliation 不可信。",
        "ERROR",
        "QUARANTINE",
        "金額不可用 binary float 或猜測修補。",
        "確認零額訂單及負數退款是否可能。",
        "接受資料的 amount 均可精確解析且符合核准 domain。",
    ),
    detector(
        "ORD-011",
        "orders",
        "coupon_discount 無法解析為 Decimal 或為負數",
        "net amount 可能被高估或低估。",
        "ERROR",
        "QUARANTINE",
        "折扣語意需保守處理。",
        "確認負折扣、補款與 coupon 單位語意。",
        "折扣均可精確解析並符合核准 domain。",
    ),
    detector(
        "ORD-012",
        "orders",
        "order timestamp 不符合 canonical 帶 offset ISO 8601 raw format",
        "未正規化會使事件排序、FX business date 與 as-of 分析使用不一致 timezone。",
        "WARNING",
        "NORMALIZE",
        "本來源的 YYYY/MM/DD HH:MM:SS 依台灣業務與 updated_at +08:00 證據補 Asia/Taipei。",
        "規則只限本題來源；保留 raw value 並加 timezone_assumed=true。",
        "canonical type 為 TIMESTAMPTZ；欄位別 noncanonical count 與 flag count 一致。",
    ),
    detector(
        "ORD-013",
        "orders",
        "updated_at 早於 order_created_at",
        "事件時間線不可能或來源時鐘語意不一致。",
        "ERROR",
        "QUARANTINE",
        "不應自行交換時間。",
        "確認 updated_at 的上游語意與 timezone。",
        "異常時間線全數依核准策略處理。",
    ),
    detector(
        "ORD-014",
        "orders",
        "departure_date 早於 order 建立日期",
        "旅遊履約與 lead-time 分析失真。",
        "ERROR",
        "QUARANTINE",
        "可能是錯誤日期或特殊補登，需確認。",
        "確認是否允許事後補登訂單。",
        "負 lead-time 全數有明確處理結果。",
    ),
    detector(
        "ORD-015",
        "orders",
        "order 的 member_id 不存在於會員來源",
        "會員維度關聯及會員分析會缺失。",
        "ERROR",
        "QUARANTINE",
        "Phase 1 不先建立 unknown member。",
        "決定 unknown member 或 quarantine 策略。",
        "所有接受 order 可關聯會員，或明確對應核准 unknown。",
    ),
    detector(
        "ORD-016",
        "orders",
        "order 的 product_id 不存在於產品來源",
        "產品維度關聯及營收分析會缺失。",
        "ERROR",
        "ACCEPT",
        "保留 raw order；Phase 2 候選使用 Unknown Product surrogate key 加 quality flag。",
        "Phase 1 不建立 Unknown Product，也不因 reference missing 刪除 order。",
        "所有 missing reference 保留 flag，Phase 2 可關聯唯一 Unknown Product candidate。",
    ),
    detector(
        "ORD-017",
        "orders",
        "非 TWD order 在 order_created_date 找不到 FX rate",
        "TWD 金額無法依候選日期規則換算。",
        "ERROR",
        "QUARANTINE",
        "檢查採候選 FX date，尚非正式 ETL 規則。",
        "確認 FX date、TWD 處理與 missing-rate policy。",
        "依核准 FX 規則後 coverage 為 100% 或全數隔離。",
    ),
    detector(
        "ORD-018",
        "orders",
        "候選 terminal-looking status 後仍出現不同狀態的 transition",
        "可能是合法 correction、重開、亂序或 ID collision；題目未提供正式 state machine。",
        "WARNING",
        "ACCEPT",
        "不使用線性 rank；完整 transition pairs 只作 profiling evidence。",
        "需要上游正式 state machine；不得宣稱 completed/cancelled 絕對 terminal。",
        "取得正式 state machine 後再對 transition pair 分類，現階段不 quarantine。",
    ),
    detector(
        "ORD-019",
        "orders",
        "order/member/product key 格式不符合候選 contract",
        "business key 或 reference join 可能失敗。",
        "ERROR",
        "QUARANTINE",
        "不自行改寫來源 key。",
        "確認是否存在合法 legacy key 格式。",
        "所有接受 key 符合核准格式或具明確 mapping。",
    ),
    detector(
        "ORD-020",
        "orders",
        "coupon_discount 大於候選 FX 規則換算的 gross TWD",
        "若折扣單位確為 TWD，net amount 將為負數。",
        "ERROR",
        "QUARANTINE",
        "使用 Decimal 與 order_created_date rate 檢查，但金額公式尚待確認。",
        "確認 amount 是否已含 quantity、FX date、rounding 與折扣語意。",
        "依核准公式後所有負 net amount 均有明確處理。",
    ),
    detector(
        "ORD-021",
        "orders",
        "base order_created_date 不在 README 宣告的 2026-05-01 至 2026-06-30",
        "base 範圍 reconciliation 可能失真。",
        "ERROR",
        "QUARANTINE",
        "base 日期範圍直接來自題目 README。",
        "確認 base 範圍是否以建立日定義且邊界是否 inclusive。",
        "base 接受資料均符合核准來源期間。",
    ),
    detector(
        "ORD-022",
        "orders",
        "incremental event 的 order_created_date 與 batch label date 不同",
        "這可代表既有訂單狀態更新；若誤當新訂單會錯估新增量。",
        "INFO",
        "ACCEPT",
        "題目明示 incremental 可包含狀態更新，故先接受並量化。",
        "確認 batch date、event date 與 order created date 的正式語意。",
        "增量流程分辨新訂單與既有訂單事件，且兩類筆數可 reconciliation。",
    ),
    detector(
        "ORD-023",
        "orders",
        "候選 gross TWD 不在產品牌價乘 quantity 的 0.5 至 2 倍",
        "可能是金額放大、單位錯誤或合法特殊價格；直接納入會扭曲營收。",
        "WARNING",
        "QUARANTINE",
        "以 Decimal 乘法做可重現 outlier detector，0.5–2 倍只是待核准候選範圍。",
        "確認 amount 是否為整單金額、quantity 語意及合理價格容忍區間。",
        "依核准價格規則重跑，所有 outlier 都有可追溯處理。",
    ),
    detector(
        "ORD-024",
        "orders",
        "departure_date 無法解析為 canonical ISO date",
        "出發日與 lead-time 分析可能失真。",
        "ERROR",
        "QUARANTINE",
        "將 date control 與 timestamp normalization finding 分離。",
        "來源沒有其他日期格式或修補規則；Phase 1 不自行補值。",
        "所有接受 departure_date 均符合 YYYY-MM-DD 且可解析。",
    ),
    detector(
        "MEM-001",
        "members",
        "完全相同的會員快照列重複",
        "可能重複產生會員版本或放大 join。",
        "ERROR",
        "QUARANTINE",
        "Phase 1 保留原始列，不任意 drop_duplicates。",
        "確認重複快照 winner policy。",
        "候選 snapshot key 唯一且 loser lineage 保留。",
    ),
    detector(
        "MEM-002",
        "members",
        "同一 member_id、extract_date 有多筆快照",
        "同日可能產生多個版本候選。",
        "ERROR",
        "QUARANTINE",
        "來源沒有同日 sequence。",
        "確認同日 snapshot tie-breaker。",
        "每個 snapshot key 唯一或整組隔離。",
    ),
    detector(
        "MEM-003",
        "members",
        "同一 member_id、extract_date 有不同 payload",
        "無法判斷同日權威會員狀態。",
        "CRITICAL",
        "QUARANTINE",
        "相同快照日期衝突不能任意選取。",
        "取得上游 sequence 或決定整組隔離。",
        "每個 snapshot key 恰有一個核准 payload。",
    ),
    detector(
        "MEM-004",
        "members",
        "member_id 格式不符合候選 contract",
        "key join 與 lineage 可能失敗。",
        "ERROR",
        "QUARANTINE",
        "不自行改寫 business key。",
        "確認是否有合法 legacy key。",
        "所有接受 member_id 符合核准格式。",
    ),
    detector(
        "MEM-005",
        "members",
        "member_level 不在候選 contract domain",
        "會員分級分析可能漏列或拆分類。",
        "WARNING",
        "NORMALIZE",
        "可能是 alias，需保留 raw 並確認 mapping。",
        "確認會員等級合法清單與 alias。",
        "正規化後 level 僅含核准 domain。",
    ),
    detector(
        "MEM-006",
        "members",
        "會員日期 parse failure",
        "年齡、年資與 snapshot 排序不可用。",
        "ERROR",
        "QUARANTINE",
        "日期無權威修補來源。",
        "確認空 birth_date 是否允許及日期格式。",
        "所有接受日期可解析，nullable 規則符合 contract。",
    ),
    detector(
        "MEM-007",
        "members",
        "birth/register/extract 日期先後不合理",
        "年齡與會員年資分析失真。",
        "ERROR",
        "QUARANTINE",
        "不可自行改寫日期。",
        "確認最小註冊年齡與歷史資料邊界。",
        "所有接受 snapshot 符合核准 chronology。",
    ),
    detector(
        "MEM-008",
        "members",
        "相鄰快照出現 null 與 non-null transition",
        "SCD change detection 若非 null-safe 會遺漏變更。",
        "INFO",
        "ACCEPT",
        "先量化變化，不在 Phase 1 實作 SCD2。",
        "確認各 attribute 的 null 語意與 tracked 狀態。",
        "Phase 2 以 null-safe 比較測試涵蓋已觀察 transition。",
    ),
    detector(
        "MEM-009",
        "members",
        "同一 member_id 有兩個以上不同的非 sentinel birth_date",
        "無權威規則可判定哪個非 sentinel 出生日期代表正確 identity。",
        "ERROR",
        "QUARANTINE",
        "只有多個不同非 sentinel 日期才構成 canonical identity ambiguity。",
        "不得依 earliest、latest、檔案順序或 row hash 選擇生日。",
        "所有 ambiguity member 整組隔離；non-sentinel distinct count 可重現。",
    ),
    detector(
        "MEM-010",
        "members",
        "相鄰快照的 member_level 或 city 發生變化",
        "後續歷史維度若覆寫會遺失可分析的會員狀態變化。",
        "INFO",
        "ACCEPT",
        "本檢查只量化變化，不建立 SCD2 或指定 tracked attributes。",
        "人工決策採 Phase 2 候選 SCD2 tracked attributes；本階段只 ACCEPT 與量化。",
        "Phase 2 以版本測試覆蓋所有已觀察 attribute change。",
    ),
    detector(
        "MEM-011",
        "members",
        "parse-valid birth_date sentinel 1900-01-01",
        "若當成真實生日，年齡分析、identity 判定與日期維度範圍會失真。",
        "WARNING",
        "NORMALIZE",
        "大量會員共享極端日期；保留 raw value 並將 canonical birth_date 正規化為 NULL。",
        "只有 sentinel 的會員仍可進維度；sentinel 加唯一非 sentinel 視為 correction candidate。",
        "canonical NULL、birth_date_sentinel／birth_date_unknown 與 raw lineage counts 一致。",
    ),
    detector(
        "PROD-001",
        "products",
        "完全相同的產品列重複",
        "產品 join 可能倍增。",
        "ERROR",
        "QUARANTINE",
        "不任意去重。",
        "確認重複產品 winner policy。",
        "接受產品 business key 唯一。",
    ),
    detector(
        "PROD-002",
        "products",
        "product_id 重複",
        "產品關聯可能一對多。",
        "ERROR",
        "QUARANTINE",
        "主檔 key 應唯一。",
        "確認是否存在產品版本語意。",
        "接受產品 business key 唯一。",
    ),
    detector(
        "PROD-003",
        "products",
        "product_id 格式不符合候選 contract",
        "產品 join 與 lineage 可能失敗。",
        "ERROR",
        "QUARANTINE",
        "不自行改寫 key。",
        "確認合法 legacy product key。",
        "所有接受 product_id 符合核准格式。",
    ),
    detector(
        "PROD-004",
        "products",
        "產品必要文字欄位為 blank",
        "產品分類與目的地分析缺失。",
        "ERROR",
        "QUARANTINE",
        "無權威文字可補入。",
        "確認各文字欄位是否必填。",
        "接受產品必要欄位均非 blank。",
    ),
    detector(
        "PROD-005",
        "products",
        "trip_days、base_price_twd 或 is_active 不符合 domain",
        "行程與價格分析不可信。",
        "ERROR",
        "QUARANTINE",
        "數值與旗標不可猜測修補。",
        "確認零天、零價與 active alias 是否可能。",
        "接受產品數值及旗標符合核准 contract。",
    ),
    detector(
        "PROD-006",
        "products",
        "不同 product_id 具有完全相同的產品描述與數值",
        "可能是合法不同 SKU，也可能造成產品層級重複分析。",
        "INFO",
        "ACCEPT",
        "business key 不同時不應自行合併。",
        "確認相同描述是否代表不同可售 SKU。",
        "保留 key 唯一性並以核准產品 identity 規則驗證。",
    ),
    detector(
        "FX-001",
        "fx_rates",
        "rate_date、currency key 重複",
        "FX join 可能倍增金額。",
        "ERROR",
        "QUARANTINE",
        "匯率 key 應唯一。",
        "確認是否有 intraday rate 或來源優先序。",
        "每個核准 FX key 恰有一筆 rate。",
    ),
    detector(
        "FX-002",
        "fx_rates",
        "同一 FX key 有不同 rate",
        "同筆 order 可能換算出不同 TWD 金額。",
        "CRITICAL",
        "QUARANTINE",
        "沒有 rate timestamp 或來源優先序。",
        "確認權威 rate selection。",
        "每個核准 FX key 恰有一個 rate。",
    ),
    detector(
        "FX-003",
        "fx_rates",
        "FX 日期、幣別或 rate 不符合 contract",
        "FX coverage 與金額換算不可信。",
        "ERROR",
        "QUARANTINE",
        "rate 必須為正 Decimal 且 currency 已核准。",
        "確認支援幣別與 rate domain。",
        "接受 FX row 均符合核准 contract。",
    ),
    detector(
        "FX-004",
        "fx_rates",
        "各幣別在自身日期範圍內有日曆缺口",
        "若 FX 規則要求每日 rate，部分訂單可能無法換算。",
        "WARNING",
        "QUARANTINE",
        "週末/假日是否允許 carry-forward 尚未確認。",
        "確認 FX calendar 與 carry-forward 規則。",
        "依核准 calendar 規則後不存在未解釋缺口。",
    ),
)


DETECTOR_BY_ID = {item.issue_id: item for item in DETECTORS}
